// JsFromRoutes CacheKey e5921e64d910ed60c1c16320939e0bfe
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
export { default as announcements } from '~/api/AnnouncementsApi'
